apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
    app: front-tier
spec:
  containers:
    - image: nginx:latest
      name: nginx-container
      ports:
        - containerPort: 80
